config/routes.rb
Rails.application.routes.draw do
  mount HighlandsAuth::Engine => "/highlands_sso", :as => "auth"

  # Offers
  resources :offers, only: [:index, :show]

  # Invoices
  resources :invoices, only: [:new, :show] do
    # LineItems
    resources :line_items, only: [:destroy]
  end

  # PaymentMethod
  resources :payment_methods, only: [:new, :create, :destroy]

  # Checkouts
  resources :checkouts

  resources :visitor, only: [:index]

  ActiveAdmin.routes(self)
  root to: "visitor#index"
  namespace :api do
    namespace :v1 do
      get 'app/me', to: 'app#me'
      resources :offers, only: [:create, :show, :index, :update]
    end
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  # Checkout exceptions
  rescue_from Checkout::TransactionError, with: :flash_and_redirect
  # Coupon exceptions
  rescue_from Coupon::NotFound, with: :flash_and_redirect
  # Offer exceptions
  rescue_from Offer::DueOnExpired, with: :flash_and_redirect
  rescue_from Offer::DeferrableNotAllowed, with: :flash_and_redirect
  # LineItem exceptions
  rescue_from LineItem::CouponOnlyValidBeforePayment, with: :flash_and_redirect
  # PaymentMethod exceptions
  rescue_from PaymentMethod::NoPaymentMethod, with: :flash_and_redirect
  # Spreedly Exceptions
  rescue_from Spreedly::TransactionCreationError, with: :flash_and_redirect

  def create
    find_offer_coupon_and_invoice
    redirect_if_no_payment_method

    checkout = Checkout.new(user: current_user,
                            payment_method_id: params[:payment_method_id],
                            offer: @offer,
                            coupon: @coupon,
                            amount: params[:amount],
                            invoice: @invoice)

    message = checkout.pay
    flash[:success] = message
    redirect_to @invoice
  end

  private

  def find_offer_coupon_and_invoice
    @invoice = Invoice.find(params[:invoice_id])
    # raise an exception here when the offer does not exist
    @offer = Offer.find(params[:offer_id])
    coupon_code = params[:coupon]
    @coupon = Coupon.find_by(code: coupon_code.try(:downcase), offer: @offer)
    raise Coupon::NotFound, 'This coupon does not exist' if coupon_code && !@coupon
  end

  def redirect_if_no_payment_method
    # If user has no payment method yet redirect to payment method once the payment method is added,
    # go back to buy and have the offer_id as params
    redirect_to(new_payment_method_path) unless payment_method_or_coupon
  end

  def payment_method_or_coupon
    current_user.payment_method_present? || @coupon
  end
end

app/views/checkouts/_coupon_form.html.haml
= form_tag(checkouts_path, class: "pure-form") do
  %fieldset
    .pure-u-1-4
      %h5 Coupon
      = text_field_tag :coupon,nil, {class: "pure-input-1-4"}
      = hidden_field_tag :offer_id, @offer.id
      = hidden_field_tag :invoice_id, @invoice.id
      %button.pure-button{type: "submit"} Apply Coupon

app/views/checkouts/_invoice.html.haml
%div
  %table.pure-table.pure-table-horizontal
    %thead
      %tr
        %th Item
        %th Date
        %th Amount
    %tbody
      - if @offer.amount?
        %tr.pure-table-odd
          %td
            %strong Offers
          %td
          %td
        - @invoice.line_items.offers.each do |li|
          %tr
            %td #{@invoice.offer.name} - #{li.type}
            %td= li.created_at.to_date
            %td= number_to_currency(li.amount)
        %tr
          %td
          %td
            %strong Subtotal
          %td
            %strong= number_to_currency @invoice.subtotal
      - if @offer.amount?
        %tr.pure-table-odd
          %td
            %strong Discounts
          %td
          %td
        - @invoice.line_items.discounts.each do |li|
          %tr
            %td #{@invoice.offer.name} - #{li.type}
            %td= li.created_at.to_date
            %td
              \-
              = number_to_currency li.amount
              = link_to 'X', invoice_line_item_path(@invoice.id,li.id), method: :delete, id: "delete-coupon-#{li.id}", data: {confirm: 'Are you sure?'}
      - if @offer.amount?
        %tr
          %td
          %td
            %strong Total
          %td
            %strong= number_to_currency @invoice.total
      - unless @invoice.payments.count.zero?
        %tr.pure-table-odd
          %td
            %strong Payments
          %td
          %td
      - @invoice.payments.each do |payment|
        =# change this class to payment (singluar)
        %tr.payments
          %td
            Payment
            %div
              %small= payment.payment_method
          %td= payment.created_at.to_date
          %td
            \-
            = number_to_currency payment.amount
      - unless @invoice.payments.count.zero?
        %tr
          %td
          %td
            %strong Total Payments
          %td
            %strong - #{number_to_currency @invoice.balance_paid}
      - if @offer.amount?
        %tr
          %td
          %td
            %strong Amount Remaining
          %td
            %strong= number_to_currency @invoice.balance_remaining

app/views/checkouts/_make_payment_form.html.haml
= form_tag(checkouts_path, class: "pure-form", id: "payment-form") do
  %fieldset
    %div.pure-u-1-4
      %h5 Payment
      - if @offer.deferrable? && @offer.amount
        = number_field_tag :amount, format_amount(@balance_remaining), {min: 0.00, max: @balance_remaining, step: :any, class: "pure-input-1-4"}
      - else
        = hidden_field_tag :amount, @balance_remaining
      - unless @offer.amount?
        = number_field_tag :amount, 0.00, {min: 0.00, step: :any, class: "pure-input-1-4"}
      = hidden_field_tag :offer_id, @offer.id
      = hidden_field_tag :invoice_id, @invoice.id
      - if @payment_methods.any?
        %div
          %ul
            = collection_radio_buttons(nil, :payment_method_id, @payment_methods, :id, :to_s, required: :required, checked: @payment_methods.first.id) do |button|
              %li
                = button.label { button.radio_button(required: 'required') + " #{button.text}" }
                = link_to 'X', payment_method_path(button.value), method: :delete, id: "delete-payment-method-#{button.value}", data: {confirm: 'Are you sure?'}
        %div
          = link_to 'Add a new card', new_payment_method_path
          = render 'checkouts/payment_button'
      - else
        %div= link_to 'Add a Payment Method', new_payment_method_path

app/views/checkouts/_payment_button.html.haml
#make-payment-button
  %button.pure-button{type: "submit"}
    = @offer.deferrable? ? 'Make Payment' : 'Pay full amount'