config/routes.rb
Rails.application.routes.draw do
  mount HighlandsAuth::Engine => "/highlands_sso", :as => "auth"

  # Offers
  resources :offers, only: [:index, :show]

  # Invoices
  resources :invoices, only: [:new, :show] do
    # LineItems
    resources :line_items, only: [:destroy]
  end

  # PaymentMethod
  resources :payment_methods, only: [:new, :create, :destroy]

  # Checkouts
  resources :checkouts

  resources :visitor, only: [:index]

  ActiveAdmin.routes(self)
  root to: "visitor#index"
  namespace :api do
    namespace :v1 do
      get 'app/me', to: 'app#me'
      resources :offers, only: [:create, :show, :index, :update]
    end
  end

end

app/models/offer.rb
class Offer < ApplicationRecord
  # An Offer is a thing people can pay towards. It has a required name and description, and belongs
  # to an application.

  # It has a due_on which is the final day it can be paid towards.

  # Non required Amount field can set a price for the offer, but also can be left unset so that some
  # one can donate any amount

  # The deferrable boolean allows multiple payments to be made against an offer when true, or when
  # false the full amount is due in a single transaction.

  DueOnExpired = Class.new(StandardError)
  DeferrableNotAllowed = Class.new(StandardError)

  belongs_to :manager
  has_many :coupons, dependent: :destroy
  has_many :invoices

  validates :manager, presence: true
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/api/v1/offers_controller.rb
class Api::V1::OffersController < Api::V1::ApiBaseController
  def show
    @offer = Offer.find(params[:id])
    render json: @offer
  end

  def index
    @offers = @manager.offers
    render json: @offers
  end

  def update
    @offer = @app.offers.find(params[:id])
    if @offer.update(offer_params)
      render json: @offer, status: 201
    else
      render json: { error: @offer.errors }, status: 422
    end
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.manager = @manager
    if @offer.save
      render json: @offer
    else
      render json: { error: @offer.errors }, status: 422
    end
  end

  private

  def offer_params
    params.require(:offer).permit %i[description name due_on amount deferrable]
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_redirect_path, only: [:show]
  before_action :authenticate_user!

  rescue_from Manager::NotInSession, with: :flash_and_redirect

  def index
    if @manager
      @offers = @manager.offers
    else
      raise Manager::NotInSession, 'Please, specify the manager'
    end
  end

  def show
    @offer = @manager.offers.find(params[:id])
    @invoices = Invoice.where(offer: @offer, user: current_user)
  end
end

app/views/offers/index.html.haml
%h3 Offers
%ul
  - @offers.each do |offer|
    %li= link_to offer.name, offer_path(offer)

app/views/offers/show.html.haml
%div.pure-g.pure-u-1
  %h1= @offer.name
  %div
    %h5 Description
    = @offer.description
  %div
    - if @offer.amount?
      %h5 Amount
      = number_to_currency(@offer.amount)
  - if @invoices.any?
    %h3 Invoices
    %table.pure-table.pure-table-horizontal
      %thead
        %tr
          %th Invoice ID
          %th Created At
          %th Status
      %tbody
        - @invoices.each do |invoice|
          %tr
            %td= link_to invoice.id, invoice_path(invoice)
            %td= invoice.created_at
            %td
              %b= invoice.status
  - else
    %h3 You haven't purchased this offer.
  = link_to 'Purchase', new_invoice_path(offer_id: params[:id])